# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
