# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_maincategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
