# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_maincategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCategories',
        ),
    ]
