# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maincategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=300)),
                ('looking_for', models.CharField(max_length=50)),
                ('job_category', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=500)),
                ('job_location_details', models.TextField()),
                ('job_start_date_time', models.DateTimeField(auto_now_add=True)),
                ('job_days', models.CharField(max_length=50)),
                ('job_length', models.FloatField(null=True)),
                ('job_showcase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Business_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.FloatField(null=True)),
                ('enable_text', models.CharField(max_length=200)),
                ('moto', models.TextField()),
                ('line_of_work', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('package_price', models.FloatField(null=True)),
                ('package_details', models.TextField()),
                ('business_address', models.CharField(max_length=200)),
                ('street_num', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('days_to_work', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednsday', 'Wednsday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
