# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201031_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_Available_Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('days_to_work', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednsday', 'Wednsday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Package_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('package_name', models.CharField(choices=[('Portrait', 'Portrait'), ('Family', 'Family'), ('Graduation', 'Graduation')], max_length=200)),
                ('package_price', models.FloatField(null=True)),
                ('package_details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pro_business_info',
            name='days_to_work',
        ),
        migrations.RemoveField(
            model_name='pro_business_info',
            name='package_details',
        ),
        migrations.RemoveField(
            model_name='pro_business_info',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='pro_business_info',
            name='package_price',
        ),
        migrations.AlterField(
            model_name='pro_business_info',
            name='enable_text',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200),
        ),
        migrations.AlterField(
            model_name='pro_business_info',
            name='line_of_work',
            field=models.CharField(choices=[('Photographer', 'Photographer'), ('Videographer', 'Videographer'), ('Both', 'Both')], max_length=200),
        ),
    ]
